name: Homes
version: '${version}'
main: de.pqtriick.homes.Homes
api-version: 1.16
authors: [ pqtriick ]
description: Set custom homes

libraries:
  - net.kyori:adventure-api:4.14.0
  - net.kyori:adventure-platform-bukkit:4.3.1
  - net.kyori:adventure-text-minimessage:4.14.0
  - net.kyori:adventure-text-serializer-legacy:4.14.0
  - net.kyori:adventure-text-serializer-gson:4.14.0
  - net.kyori:adventure-text-serializer-plain:4.14.0

commands:
  addhome:
  homes:
  checkhomes:
  reloadvalues:

